spring:
  application:
    name: product-service

server:
  port: 10002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

#logging:
#  level:
#    root: debug
#
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true