spring:
  application:
    name: price-service

server:
  port: 10003

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"