spring:
  application:
    name: order-service

server:
  port: 10001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true